/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ArticulosRouteImport } from './routes/articulos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticulosIndexRouteImport } from './routes/articulos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as ArticulosSlugRouteImport } from './routes/articulos.$slug'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminArticulosIdRouteImport } from './routes/admin.articulos.$id'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosRoute = ArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticulosRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosSlugRoute = ArticulosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticulosRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticulosIdRoute = AdminArticulosIdRouteImport.update({
  id: '/articulos/$id',
  path: '/articulos/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articulos': typeof ArticulosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/admin/articulos/$id': typeof AdminArticulosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/articulos': typeof ArticulosIndexRoute
  '/admin/articulos/$id': typeof AdminArticulosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articulos': typeof ArticulosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/admin/articulos/$id': typeof AdminArticulosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articulos'
    | '/contacto'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/admin/categorias'
    | '/articulos/$slug'
    | '/uploads/$'
    | '/admin/'
    | '/articulos/'
    | '/admin/articulos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/admin/categorias'
    | '/articulos/$slug'
    | '/uploads/$'
    | '/admin'
    | '/articulos'
    | '/admin/articulos/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articulos'
    | '/contacto'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/admin/categorias'
    | '/articulos/$slug'
    | '/uploads/$'
    | '/admin/'
    | '/articulos/'
    | '/admin/articulos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticulosRoute: typeof ArticulosRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos': {
      id: '/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof ArticulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof ArticulosRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/$slug': {
      id: '/articulos/$slug'
      path: '/$slug'
      fullPath: '/articulos/$slug'
      preLoaderRoute: typeof ArticulosSlugRouteImport
      parentRoute: typeof ArticulosRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articulos/$id': {
      id: '/admin/articulos/$id'
      path: '/articulos/$id'
      fullPath: '/admin/articulos/$id'
      preLoaderRoute: typeof AdminArticulosIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticulosIdRoute: typeof AdminArticulosIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticulosIdRoute: AdminArticulosIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticulosRouteChildren {
  ArticulosSlugRoute: typeof ArticulosSlugRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
}

const ArticulosRouteChildren: ArticulosRouteChildren = {
  ArticulosSlugRoute: ArticulosSlugRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
}

const ArticulosRouteWithChildren = ArticulosRoute._addFileChildren(
  ArticulosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticulosRoute: ArticulosRouteWithChildren,
  ContactoRoute: ContactoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  UploadsSplatRoute: UploadsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
