/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FrasesRouteImport } from './routes/frases'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ArticulosRouteImport } from './routes/articulos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticulosIndexRouteImport } from './routes/articulos.index'
import { Route as ArticulosSlugRouteImport } from './routes/articulos.$slug'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FrasesRoute = FrasesRouteImport.update({
  id: '/frases',
  path: '/frases',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosRoute = ArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticulosRoute,
} as any)
const ArticulosSlugRoute = ArticulosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticulosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articulos': typeof ArticulosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/frases': typeof FrasesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/frases': typeof FrasesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/articulos': typeof ArticulosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articulos': typeof ArticulosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/frases': typeof FrasesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/articulos/': typeof ArticulosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articulos'
    | '/contacto'
    | '/frases'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/articulos/$slug'
    | '/articulos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/frases'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/articulos/$slug'
    | '/articulos'
  id:
    | '__root__'
    | '/'
    | '/articulos'
    | '/contacto'
    | '/frases'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/articulos/$slug'
    | '/articulos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticulosRoute: typeof ArticulosRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  FrasesRoute: typeof FrasesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frases': {
      id: '/frases'
      path: '/frases'
      fullPath: '/frases'
      preLoaderRoute: typeof FrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos': {
      id: '/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof ArticulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof ArticulosRoute
    }
    '/articulos/$slug': {
      id: '/articulos/$slug'
      path: '/$slug'
      fullPath: '/articulos/$slug'
      preLoaderRoute: typeof ArticulosSlugRouteImport
      parentRoute: typeof ArticulosRoute
    }
  }
}

interface ArticulosRouteChildren {
  ArticulosSlugRoute: typeof ArticulosSlugRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
}

const ArticulosRouteChildren: ArticulosRouteChildren = {
  ArticulosSlugRoute: ArticulosSlugRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
}

const ArticulosRouteWithChildren = ArticulosRoute._addFileChildren(
  ArticulosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticulosRoute: ArticulosRouteWithChildren,
  ContactoRoute: ContactoRoute,
  FrasesRoute: FrasesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
